### ISSUE TITLE
Build error: Use of unresolved identifier

### ISSUE THREAD

**Issue by hffmnn** [snipsco/snips-platform-swift#21]
Hi there.

When trying to build the `SnipsPlatform-iOS` (current `master` at `af75f24006e19e6c39ac40eb865aa62a5ab17cad`) from within `SnipsPlatformDemo.xcworkspace` the following errors pops up in `Ontology.swift`:
Use of unresolved identifier `SNIPS_SLOT_VALUE_TYPE_MUSICALBUM`
Use of unresolved identifier `SNIPS_SLOT_VALUE_TYPE_MUSICARTIST`
Use of unresolved identifier `SNIPS_SLOT_VALUE_TYPE_MUSICTRACK`

Looking into `libsnips_megazord.h` it looks like these are not defined.

Commenting them out seems to make the project build as expected.

Any ideas?

Another question would be if it is possible to build `SnipsPlatform-macOS`? The build stops because `download_core.sh` only supports downloading `ios`.

Thanks and Regards,
Christian

**Comment by nebuto** [comment]
Hi @hffmnn 

What happens here is that our CI pushes new tags for RC versions, but does not update the version number inside the `download_core.sh` until we release a publicly stable Snips platform. Thus the `libsnips_megazord.h` and `libsnips_megazord.a` downloaded from `download_core.sh` is not the latest one. The fix is on our roadmap.

In the meantime you can resolve the iOS build two ways :
• In `download_core.sh`, update the version to the latest tag: `VERSION=0.60.0-RC1`
• Comment out the slots like you already did
• Pull the latest stable tag `0.59.0` instead of `master`

You can potentially also encounter errors from the NLU engine not beeing able to load the assistant because of a NLU model version mismatch, use the `0.59.0` version to resolve this.

As for the macOS build, it is not usable as of yet, we haven't released the two dependencies necessary, `libsnips_megazord.dylib` & `libsnips_kaldi.dylib` to the public. No release date for now. I'll keep you posted when we do.

**Comment by hffmnn** [comment]
Thanks for all the info. Will retry soon.
