### ISSUE TITLE
Listening in Background

### ISSUE THREAD

**Issue by andrenatal** [snipsco/snips-platform-swift#25]
Is there a way to keep the app running and listening while in background?

**Comment by klefevre** [comment]
It seems that you can. See this question on SO: https://stackoverflow.com/questions/3848172/ios-multitasking-for-an-audio-recording-application .

On iOS we leave the responsability to implementers to provide audio buffers from any source he wants.

In the sample code, we showcase how you could easily use the `AVFoundation` API but there are multiple way to get audio from the microphone. Note that we basically use what was provided in this Apple sample code available in this article: https://developer.apple.com/documentation/speech/recognizing_speech_in_live_audio .

I consider this question off-topic because it's not a Snips related question but rather an Apple one and I invite you to ask this question on SO or on the Apple dev forum.
