### ISSUE TITLE
iOS 11.3 build failure in Clibsnips_megazord

### ISSUE THREAD

**Issue by kiliankoe** [snipsco/snips-platform-swift#5]
Hi 😊,
when trying to build SnipsPlatform with the current Xcode 9.3b4 targeting the iOS 11.3 SDK the build fails on the following error in `libsnips_megazord.h`.

```c
typedef enum {
  ACTION = 1,                // <- Redefinition of 'ACTION'
  NOTIFICATION = 2,
} CSessionInitType;
```

**Comment by klefevre** [comment]
I knew this would happened one day... Well we'll try to fix this in the release of the platform. Thank you for pointing out this.

**Comment by NightIsland** [comment]
I'm having the same problem. This is currently unusable on iOS.
ETA for fix?

**Comment by klefevre** [comment]
Yes, we'll release the fix tomorrow.

**Comment by klefevre** [comment]
Hey guys, thanks for the feedback and the wait for this fix. It took more time than expected because we have updated how we generate our headers in the entire codebase of the Snips platform.

The latest release `0.55.3-RC1` fixes this issue. So if you use Cartage or Cocoapods you'll have to force the version:

On Cocoapods:
```
pod 'SnipsPlatform', '~> 0.55.3-RC1'
```

On Cartage:
```
github "https://github.com/snipsco/Specs" "0.55.3-RC1"
```

If you're curious on what was done you can check this PR of one of the component's platform : snipsco/snips-nlu-rs#39

Cheers
