### ISSUE TITLE
Nothing recognized or no audio

### ISSUE THREAD

**Issue by radinsky** [snipsco/snips-platform-swift#7]
Hi

I've succeeded to build and run (on both simulator and real device iPhone 7) the demo, in debug I see no errors, ARS NLU initialized correctly, the dialog also initializing correctly, but it looks like the app is listening but not hearing me. When run on real device, it asked to use microphone and I accepted, but still nothing detected, not hotword and not the intents. 

What am I missing?

**Comment by klefevre** [comment]
Hi @radinsky 

It's hard to debug without a bit more context. First questions that come to me are:
- Did you try to enable internal logs via the `SnipsPlatform` class constructor ?
- Did you try to trigger manually the hotword ? If yes, when you speak you should see ASR results. What's the output ?

Could you send some logs to see what could happen ?

**Comment by SebanSunny** [comment]
I do have the same issue. @klefevre Could you elaborate on the steps that you've mentioned above?
I've attached the log file from a single session.
[test.log](https://github.com/snipsco/snips-platform-swift/files/2153126/test.log)

**Comment by klefevre** [comment]
Hi @SebanSunny
Thanks for the logs it will help me debug this issue for sure.
I’ll get informed when I’ll have news!

Thanks a lot

**Comment by klefevre** [comment]
@SebanSunny @radinsky Is there any chance you can send me your assistant to try to reproduce your setup ?
I tried again today with a freshly downloaded assistant. And everything worked fine both on the simulator and a real device (iPhone 6S in my case).

**Comment by SebanSunny** [comment]
Sure.
@klefevre 
[assistant.zip](https://github.com/snipsco/snips-platform-swift/files/2164991/assistant.zip)

**Comment by SebanSunny** [comment]
@klefevre I downloaded the Demo project from Github (no changes made in the code) and copied this assistant into it an ran it. ACR is still not capturing the text from the audio.

**Comment by klefevre** [comment]
@SebanSunny 
Did you try on a real device and/or the simulator ? Because I've reproduced the bug on the simulator but not a real device (with your assistant but also with another one).

On real devices I never had problems with the microphone but on the simulator the behavior is a bit strange (not to say weird) and I'm not sure how it really works.
If you tried on a device and had the same issue, could you tell me which model it is ?

If you check what look like the audio frames sent by the system you'll see that you'll receive only frames filled with 0... You can check that in the callback of the tap that send frames to Snips just by adding some prints.

```swift
downMixer.installTap(onBus: 0, bufferSize: 1024, format: recordingFormat) { [weak self] (buffer, when) in
    guard let frame = buffer.int16ChannelData?.pointee else { fatalError("Can't retrieve channel") }
    for i in 0..<256 {
        print("\(frame[Int(i)])", terminator:"")
    }
    print("--")
    self?.snips?.appendBuffer(buffer)
}
```

What is strange is that I made it work on a the simulator by using a bluetooth heaset. When we activate the microphone through the simulator, the headset is switched in "phone call" mode and then sounds is correctly streamed. More info here: https://help.apple.com/simulator/mac/current/#/deve63797392

Some seems to had it work by activating Siri on the simulator but it didn't work for me. Check this question on SO: https://stackoverflow.com/questions/9152355/how-do-i-test-ios-microphone-use-on-the-simulator for more info.

**Comment by SebanSunny** [comment]
Hey @klefevre , I had been trying it on simulator all these days but it's actually detecting the audio in my iPhone. I've the iPhone 5s (iOS 11.3.1).

But the voice recognition is so terrible compared to the browser version (https://console.snips.ai/), It detect even a single intent correctly.

**Comment by klefevre** [comment]
Glad to hear we're going forward :)
About the issue on your iPhone 5S, we never bench iPhone microphones and I never tested on it but the 5S seems to be known for having a bad microphone. See here: https://en.wikipedia.org/wiki/IPhone_5S#Problems
I've pretty decent results on my 6S.. =/ if you have the chance to test the SDK on a more recent device I'd love to have your feedback !

**Comment by SebanSunny** [comment]
@klefevre I'll surely test it on another device. Thanks for the amazing work, cheers!!!

**Comment by hongchaozhang** [comment]
Great work!
Is there an API for feeding a text to the SDK instead of the audio buffer? If not, is it easy to extract one by myself? Thanks in advance.

**Comment by klefevre** [comment]
Hi @hongchaozhang I'm not sure to understand what you need ... Could you explain exactly what you want to do?

**Comment by hongchaozhang** [comment]
Hi @klefevre Thanks for your response.

I see that the `SnipsPlatform` only has `appendBuffer` method to receive a piece of audio buffer as the input (`AVAudioPCMBuffer` or `[int16]` type). 
But in my app, I directly have an input string, like "What is the weather like today?" It is a text string, not voice audio. 
**My question is**: Is their an API in `SnipsPlatform` to receive a `String` as input, like `appendBuffer` receives a piece of audio buffer as the input? 
If not, is it easy for me to extract one by myself?
